name: Beta Branch CI

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # Run the stable test script on the beta channel. Since this branch will soon
  # be merged into master as our stable-targeting code, this is the key thing we
  # need to test.
  stable-tests-on-beta:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: beta
      - run: ./tool/flutter_ci_script_stable.sh
  # Verify the Android add-to-app samples build and pass tests with the beta
  # channel.
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: beta
      - run: ./tool/android_ci_script.sh
  # Verify the iOS add-to-app samples build and pass tests with the beta
  # channel.
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: beta
      - run: ./tool/ios_ci_script.sh
