name: Master Branch CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@5e1529bc12adae5b26f30f0a4046ac743d6f0c5d
        with:
          channel: ${{ matrix.flutter_version }}
      - run: ./tool/flutter_ci_script_${{ matrix.flutter_version }}.sh
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@5e1529bc12adae5b26f30f0a4046ac743d6f0c5d
        with:
          channel: stable
      - run: ./tool/android_ci_script.sh
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@9519cf1382ac8dc61ad461f7f7cb45f033220189
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@5e1529bc12adae5b26f30f0a4046ac743d6f0c5d
        with:
          channel: stable
      - run: ./tool/ios_ci_script.sh
